# Default settings

display:
  dark_mode: false
  sdl_textprovider: 'down'
  pil_textprovider: 'normal'
  pygame_textprovider: 'normal'
  pango_textprovider: 'normal'
  system_font: 'down'
  app_font: 'normal'
  fontname: 'JuniusX-Regular.ttf'
  # Not yet configurable
  md_primary_palette: 'Teal'
  md_accent_palette: 'Cyan'
account:
  username: null
  password: null
  locale: null
photos:
  start_dir: '/'
  # Not yet configurable
  filetypes: ['jpg', 'jpeg', 'jp2', 'png', 'ppm', 'gif', 'tif', 'tiff', 'pdf']
viewer:
  pdfviewer: 'webbrowser'
imageeditor:
  ie_thumbnail_size: '1000'
tesseract:
  win32url: "https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w32-setup-v5.0.0-alpha.20201127.exe"
  win64url: "https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-v5.0.0-alpha.20201127.exe"
  model: null
  psm: null
  oem: null
  tesspath: ''
  tessdatadir: ''
  tessdatadir_user_sel: 'down'
  tessdatadir_user: ''
  tessdatadir_system_sel: 'normal'
  tessdatadir_system: ''
  tessdatadir_userspecific_sel: 'normal'
  tessdatadir_userspecific: ''
  do_invert: true
# Not yet configurable
search:
  autocomplete_delay: 0.5
  autocomplete_min_chars: 3
