# Default settings

display:
  dark_mode: false
  sdl_textprovider: 'down'
  pil_textprovider: 'normal'
  pygame_textprovider: 'normal'
  pango_textprovider: 'normal'
  fontname: 'RobotoMono-Regular'
  fontsize: '21'
  # Not yet configurable
  md_primary_palette: 'Teal'
  md_accent_palette: 'Cyan'
  md_primary_palette_online: 'Lightsteelblue'
  md_accent_palette_online: 'Yellow'
account:
  username: null
  password: null
  locale: null
photos:
  start_dir: '/'
  start_dir_online: '/'
  # Not yet configurable
  filetypes: ['jpg', 'jpeg', 'jp2', 'png', 'ppm', 'gif', 'tif', 'tiff', 'pdf']
viewer:
  pdfviewer: 'webbrowser'
imageeditor:
  ie_thumbnail_size: '1000'
  load_images_async: false
tesseract:
  win32url: 'https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w32-setup-v5.0.0-alpha.20210506.exe'
  win64url: 'https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-v5.0.0-alpha.20210506.exe'
  winurl: 'https://github.com/UB-Mannheim/tesseract/wiki.html'
  online_url: 'https://ocr-bw.bib.uni-mannheim.de/TesseractXplore'
  model: null
  psm: null
  oem: null
  tesspath: ''
  tessdatadir: ''
  tessdatadir_user_sel: 'down'
  tessdatadir_user: ''
  tessdatadir_system_sel: 'normal'
  tessdatadir_system: ''
  tessdatadir_userspecific_sel: 'normal'
  tessdatadir_userspecific: ''
  do_invert: true
  model_sources_online: ['tessdata','ubma']
# Not yet configurable
search:
  autocomplete_delay: 0.5
  autocomplete_min_chars: 3
