"""
Package for controller classes. The goal is to organize these such that each controller manages
the components & state from a single .kv file.
"""
from tesseractXplor.controllers.batch_loader import BatchLoader, TaxonBatchLoader, ImageBatchLoader
from tesseractXplor.controllers.controller import Controller
from tesseractXplor.controllers.image_selection_controller import ImageSelectionController
from tesseractXplor.controllers.fulltext_view_controller import FulltextViewController
from tesseractXplor.controllers.metadata_view_controller import MetadataViewController
from tesseractXplor.controllers.observation_search_controller import ObservationSearchController
from tesseractXplor.controllers.settings_controller import SettingsController
from tesseractXplor.controllers.taxon_search_controller import TaxonSearchController
from tesseractXplor.controllers.taxon_selection_controller import TaxonSelectionController
from tesseractXplor.controllers.taxon_view_controller import TaxonViewController
from tesseractXplor.controllers.tesseract_controller import TesseractController
