# Default settings

display:
  dark_mode: false
  # Not yet configurable
  md_primary_palette: 'Teal'
  md_accent_palette: 'Cyan'
account:
  username: null
  password: null
  locale: null
photos:
  start_dir: '/'
  # Not yet configurable
  filetypes: ['jpg', 'jpeg', 'png', 'ppm', 'gif', 'tif', 'tiff']
viewer:
  pdfviewer: 'webbrowser'
tesseract:
  model: null
  psm: null
  oem: null
  tesspath: 'C:\\Program Files\\Tesseract-OCR\\tesserac.exe'
# Not yet configurable
search:
  autocomplete_delay: 0.5
  autocomplete_min_chars: 3
