# Default settings

display:
  dark_mode: false
  sdl_textprovider: 'down'
  pil_textprovider: 'normal'
  pygame_textprovider: 'normal'
  pango_textprovider: 'normal'
  # Not yet configurable
  md_primary_palette: 'Teal'
  md_accent_palette: 'Cyan'
account:
  username: null
  password: null
  locale: null
photos:
  start_dir: '/'
  # Not yet configurable
  filetypes: ['jpg', 'jpeg', 'jp2', 'png', 'ppm', 'gif', 'tif', 'tiff', 'pdf']
viewer:
  pdfviewer: 'webbrowser'
imageeditor:
  ie_thumbnail_size: '1000'
tesseract:
  model: null
  psm: null
  oem: null
  tesspath: ''
  tessdatadir: ''
  do_invert: true
# Not yet configurable
search:
  autocomplete_delay: 0.5
  autocomplete_min_chars: 3
